name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
    
      - name: Get dependencies
        run: flutter pub get
    
      - name: Build release project
        run: flutter build web --base-href=/shop/ --dart-define=BASE_URL=${{ secrets.BASE_URL }} --dart-define=PRODUCTS_PATH=${{ secrets.PRODUCTS_PATH }} --dart-define=ORDERS_PATH=${{ secrets.ORDERS_PATH }} --dart-define=AUTH_BASE_URL=${{ secrets.AUTH_BASE_URL }} --dart-define=SIGN_UP_URL_SEGMENT=${{ secrets.SIGN_UP_URL_SEGMENT }} --dart-define=SIGN_IN_URL_SEGMENT=${{ secrets.SIGN_IN_URL_SEGMENT }} --dart-define=WEB_API_KEY=${{ secrets.WEB_API_KEY }} --dart-define=FAVORITE_PRODUCTS_PATH=${{ secrets.FAVORITE_PRODUCTS_PATH }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "tiagorodriguessousa9@gmail.com"
          git config --global user.name "Tiago Rodrigues Sousa"
          cd build
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ secrets.TOKEN }}@github.com/tiagors09/shop.git" master:gh-pages
